name: testPipeline

on: push

jobs:
  pipeline:
    name: echo stuff
    runs-on: ubuntu-latest
    steps:
      - name: access repo
        uses: actions/checkout@v3
      - name: Check App
        run: |
          #Check App
          mkdir database
          
          touch console.log.txt
          
          yes | sudo apt-get install lsof && sudo apt-get install net-tools && sudo apt-get install python3-pip && sudo pip3 install flask && sudo pip3 install flask-login && sudo pip3 install flask-sqlalchemy

          export DATABASE_PATH=$(pwd)/database
          echo $DATABASE_PATH
          ls -al
          nohup python3 main.py > console.log.txt &

          cat console.log.txt
          
          netstat -an | grep ".5000 "
          if [ $? -eq 0 ]
            then
              echo "the 5000 port is listening"
              ps -ef|grep "python3 main.py"|grep -v grep|awk '{print $2}'
              kill -9 $(ps -ef|grep "python3 main.py"|grep -v grep|awk '{print $2}')
          fi
            
 
