name: testPipeline

on: push

jobs:
  pipeline:
    name: echo stuff
    runs-on: ubuntu-latest
    steps:
      - name: create directories
        run: mkdir database
      - name: create log
        run: touch console.log.txt
      - name: download packages
        run: yes | sudo apt-get install lsof && sudo apt-get install python3-pip && pip3 install flask && pip3 install flask-login && pip3 install flask-sqlalchemy
      - name: export env var
        run: export DATBASE_PATH=database
             echo $DATABASE_PATH
      - name: start application
        run: nohup python3 /website/Flask-Web-App-Tutorial-0.1.1/main.py > console.log.txt &
      - name: list log
        run: cat console.log.txt
      - name: check if port is listening
        run: 
         netstat -an | grep ".5000 "
          if [ $? -eq 0 ]
            then
              echo "the 5000 port is listening"
               ps
              kill $(lsof -t -i:5000)
              ps
            fi
            
 
