name: testPipeline

on: push

jobs:
  pipeline:
    name: echo stuff
    runs-on: ubuntu-latest
    steps:
      - name: create directories
        run: mkdir database
      - name: download packages
        run: yes | sudo apt-get install lsof && sudo apt-get install python3-pip && pip3 install flask && pip3 install flask-login && pip3 install flask-sqlalchemy
      - name: export env var
        run: export DATBASE_PATH=database
             echo $DATABASE_PATH
      - name: start application
        run: nohup python3 /website/Flask-Web-App-Tutorial-0.1.1/main.py >/var/log/website/console.log.txt &
      - name: check if port is listening
        run: 
          if lsof -Pi :8080 -sTCP:LISTEN -t >/dev/null ; then
            kill $(lsof -t -i:8080)
          else
            echo "not running"
          fi
      - name: list log
        run: echo var/log/website/console.log.txt
