name: testPipeline

on: push

jobs:
  pipeline:
    name: echo stuff
    runs-on: ubuntu-latest
    env:
      DATABASE_PATH: database
    steps:
      - name: access repo
        uses: actions/checkout@v3
      - name: create directories
        run: |
          #yghtdfytdtyd
          mkdir database
      - name: echo ipaddr
        run: |
          #dkjvdsvjkl
          export ipaddr=$(hostname -I)
          echo $ipaddr
      - name: create log
        run: |
          #yghtdfytdtyd
          touch console.log.txt
      - name: download packages
        run: |
          #yghtdfytdtyd
          yes | sudo apt-get install lsof && sudo apt-get install net-tools && sudo apt-get install python3-pip && sudo pip3 install flask && sudo pip3 install flask-login && sudo pip3 install flask-sqlalchemy
      - name: export env var
        run: |
          #yghtdfytdtyd
          echo $DATABASE_PATH
      - name: start application
        run: |
          #yghtdfytdtyd
          nohup python3 main.py > console.log.txt &
      - name: list log
        run: |
          #yghtdfytdtyd
          cat console.log.txt
      - name: check if port is listening
        run: |
          #dsjkhvbskjbdvki
          netstat -an | grep ".5000 "
          if [ $? -eq 0 ]
            then
              echo "the 5000 port is listening"
              ps
              kill -9 $(lsof -t -i:5000)
              ps
          fi
            
 
